before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - node -v
  - which node
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - npm install

rubocop:
  script:
    - bundle exec rubocop

rails_test:
  script:
    - bundle exec rails test

js_lint:
  script:
    - npm test

js_test:
  script:
    - bundle exec teaspoon
