AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# ここは日本だぞ
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Alias:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
