enums:
  existence:
    - unknown
    - exists
    - does_not_exist
  three_scale_intensity:
    - unknown
    - light
    - middle
    - heavy
  five_scale_intensity:
    - unknown
    - weak
    - rather_weak
    - mid
    - rather_strong
    - strong
  five_scale_quantity:
    - unknown
    - none
    - extremely_few
    - few
    - mid
    - many
    - extremely_many
  five_scale_mass_quantity: # mass as in "mass noun"
    - unknown
    - none
    - little
    - rather_little
    - mid
    - rather_much
    - much
  three_scale_growth:
    - unknown
    - abundant
    - normal
    - insufficient
  sex:
    - M
    - F
    - O
  closedness:
    - closed
    - open
    - other
  deixes:
    - left
    - right
air_track_organs:
  - larynx
  - trachea
  - main_bronchi
