enums:
  existence:
    - exists
    - does_not_exist
    - unknown
  three_scale_intensity:
    - light
    - mid
    - strong
  five_scale_intensity:
    - weak
    - rather_weak
    - mid
    - rather_strong
    - strong
  five_scale_quantity:
    - none
    - few
    - mid
    - many
    - extremely_many
  sex:
    - M
    - F
    - O
  closedness:
    - closed
    - open
    - other
  deixes:
    - left
    - right
