lmml_version: '0.1'
enums:
  coordinate_system:
    - distal_proximal
    - radial_ulnar
    - lateral_medial
    - front_behind
  existence:
    - unknown
    - exists
    - does_not_exist
  three_scale_intensity:
    - unknown
    - nothing
    - light
    - middle
    - heavy
  five_scale_intensity:
    - unknown
    - nothing
    - weak
    - rather_weak
    - mid
    - rather_strong
    - strong
  five_scale_quantity:
    - unknown
    - none
    - extremely_few
    - few
    - mid
    - many
    - extremely_many
  five_scale_mass_quantity: # mass as in "mass noun"
    - unknown
    - none
    - little
    - rather_little
    - mid
    - rather_much
    - much
  three_scale_growth:
    - unknown
    - abundant
    - normal
    - insufficient
  five_scale_thickness:
    - unknown
    - very_thin
    - thin
    - usual
    - thick
    - very_thick
  sex:
    - O
    - M
    - F
  closedness:
    - closed
    - open
    - other
    - unknown
  deixes:
    - left
    - right
  hardness:
    - hard
    - soft
    - unknown
  size:
    - usual
    - big
    - small
  units:
    - mg/mL
    - ng/mL
    - qualitative
  concentration:
    - undetected
    - little
    - rather_little
    - mid
    - rather_much
    - much
  substance:
    - none
    - unknown
    - water
    - saltwater
    - food
  tests:
    binary_result:
      - positive
      - negative
      - unknown
air_track_organs:
  - larynx
  - trachea
  - main_bronchi
uropaper_categories:
  leukocytes:
    values:
      -: null
      +: null
      ++: null
      +++: null
  urobilinogen:
    values:
      usual: null
      +: 2
      ++: 4
      +++: 8
      ++++: 12
    unit: mg/dL
  occult_blood_hemoglobin:
    values:
      -: null
      +-: null
      +: null
      ++: null
      +++: null
  occult_blood_erythrocytes:
    values:
      -: null
      +-: null
      +: null
      ++: null
      +++: null
  bilirubin:
    values:
      -: null
      +: null
      ++: null
      +++: null
  ketone_bodies:
    values:
      -: null
      +: null
      ++: null
      +++: null
  glucose:
    values:
      -: null
      +-: 50
      +: 100
      ++: 250
      +++: 500
      ++++: 2000
    unit: mg/dL
  protein:
    values:
      -: null
      +-: 15
      +: 30
      ++: 100
      +++: 300
      ++++: 1000
    unit: mg/dL
  nitrite:
    values:
      -: null
      weak_positive: null
      strong_positive: null
  relative_density:
    values:
      1.000: null
      1.005: null
      1.010: null
      1.015: null
      1.020: null
      1.025: null
      1.030: null
